name: publish

on: [ push ]

jobs:
  publish-win-x64:

    runs-on: windows-latest

    steps:
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - uses: actions/checkout@v2
      - name: Publish win-x64
        run: dotnet publish -c Release -r win-x64 Outseek.AvaloniaClient
      - name: Upload win-x64
        uses: actions/upload-artifact@v2
        with:
          name: outseek-win-x64
          path: Outseek.AvaloniaClient/bin/Release/net5.0/win-x64/publish

  publish-linux-x64:

    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - uses: actions/checkout@v2
      - name: Publish linux-x64
        run: dotnet publish -c Release -r linux-x64 Outseek.AvaloniaClient
      - name: Upload linux-x64
        uses: actions/upload-artifact@v2
        with:
          name: outseek-linux-x64
          path: Outseek.AvaloniaClient/bin/Release/net5.0/linux-x64/publish
